#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")"

npm install
typescript=./node_modules/typescript/lib
uglifyjs=./node_modules/uglify-js/bin

rm -f -r ../Build

echo Building Debug
mkdir -p ../Build/Debug
wrap="--wrap=0"
if [ $(uname -s) = "Darwin" ]; then
    wrap=""
fi
cp ../Source/index.html ../Build/Debug/index.html
cat << EOF >> ../Build/Debug/base64.ts
var spriteImageData = "$(base64 ../Source/Sprite.gif ${wrap})";
var fontImageData = "$(base64 ../Source/Font.gif ${wrap})";
var diamondSoundData = "$(base64 ../Source/Diamond.wav ${wrap})";
var stoneSoundData = "$(base64 ../Source/Stone.wav ${wrap})";
var stepSoundData = "$(base64 ../Source/Step.wav ${wrap})";
EOF
node ${typescript}/tsc.js -target ES5 -out ../Build/Debug/digger.js ./libex.d.ts ../Source/*.ts ../Build/Debug/base64.ts
rm ../Build/Debug/base64.ts

echo Building Release
mkdir -p ../Build/Release
cp ../Source/index.html ../Build/Release/index.html
${uglifyjs}/uglifyjs ../Build/Debug/digger.js > ../Build/Release/digger.js
